const Constants = {
  RECIEVE_PETS: 'RECIEVE_PETS',
  RECIEVE_PET: 'RECIEVE_PET',
  RECIEVE_NEW_PET: 'RECIEVE_NEW_PET',
  DELETE_PET: 'DELETE_PET',
  GET_OWNERS: 'GET_OWNERS'
}

export default Constants;
